name: car_marketplace_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  lottie: ^2.2.0
  animate_do: ^4.2.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.3.0
  path: ^1.8.3
  dots_indicator: ^3.0.0
  path_provider: ^2.1.1
  flutter_3d_controller: ^2.2.0
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  panorama: ^0.4.1
  flutter_dotenv: ^5.2.1
  svg_flutter: ^0.0.1
  flutter_inset_box_shadow: ^1.0.8
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.5
  panara_dialogs: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/3d/
    - assets/images/
    - assets/logo/
    - assets/loading/
    - assets/icons/
